import 'package:ternaku/Items/buku.dart';
import '../constants.dart';

class ListBuku {
  static List<Buku> getDummyBooks() {
    return [
      Buku(
          id: 1,
          judul: "Laut Bercerita",
          penulis: "Leila S. Chudori",
          genre: Genre.Historical,
          imgCover: "laut_bercerita",
          stok: 1,
          pages: 389,
          bahasa: "Indonesia",
          harga: "100.000",
          tipe: BookType.Fiction),
      Buku(
          id: 1,
          judul: "The Poppy War",
          penulis: "R.F Kuang",
          genre: Genre.Historical,
          imgCover: "the_poppy_war",
          stok: 1,
          pages: 413,
          bahasa: "Indonesia",
          harga: "130.000",
          tipe: BookType.NonFiction),
      Buku(
          id: 1,
          judul: "Laut Bercerita",
          penulis: "Leila S. Chudori",
          genre: Genre.Historical,
          imgCover: "laut_bercerita",
          stok: 0,
          pages: 389,
          bahasa: "Indonesia",
          harga: "100.000",
          tipe: BookType.Fiction),
      Buku(
          id: 1,
          judul: "The Poppy War",
          penulis: "R.F Kuang",
          genre: Genre.Historical,
          imgCover: "the_poppy_war",
          stok: 0,
          pages: 413,
          bahasa: "Indonesia",
          harga: "130.000",
          tipe: BookType.NonFiction),
      Buku(
          id: 1,
          judul: "Laut Bercerita",
          penulis: "Leila S. Chudori",
          genre: Genre.Historical,
          imgCover: "laut_bercerita",
          stok: 1,
          pages: 389,
          bahasa: "Indonesia",
          harga: "100.000",
          tipe: BookType.Fiction),
      Buku(
          id: 1,
          judul: "The Poppy War",
          penulis: "R.F Kuang",
          genre: Genre.Historical,
          imgCover: "the_poppy_war",
          stok: 1,
          pages: 413,
          bahasa: "Indonesia",
          harga: "130.000",
          tipe: BookType.NonFiction),
      Buku(
          id: 1,
          judul: "Laut Bercerita",
          penulis: "Leila S. Chudori",
          genre: Genre.Historical,
          imgCover: "laut_bercerita",
          stok: 0,
          pages: 389,
          bahasa: "Indonesia",
          harga: "100.000",
          tipe: BookType.Fiction),
      Buku(
          id: 1,
          judul: "The Poppy War",
          penulis: "R.F Kuang",
          genre: Genre.Historical,
          imgCover: "the_poppy_war",
          stok: 0,
          pages: 413,
          bahasa: "Indonesia",
          harga: "130.000",
          tipe: BookType.NonFiction),
      Buku(
          id: 1,
          judul: "Laut Bercerita",
          penulis: "Leila S. Chudori",
          genre: Genre.Historical,
          imgCover: "laut_bercerita",
          stok: 1,
          pages: 389,
          bahasa: "Indonesia",
          harga: "100.000",
          tipe: BookType.Fiction),
      Buku(
          id: 1,
          judul: "The Poppy War",
          penulis: "R.F Kuang",
          genre: Genre.Historical,
          imgCover: "the_poppy_war",
          stok: 1,
          pages: 413,
          bahasa: "Indonesia",
          harga: "130.000",
          tipe: BookType.NonFiction),
      Buku(
          id: 1,
          judul: "Laut Bercerita",
          penulis: "Leila S. Chudori",
          genre: Genre.Historical,
          imgCover: "laut_bercerita",
          stok: 0,
          pages: 389,
          bahasa: "Indonesia",
          harga: "100.000",
          tipe: BookType.Fiction),
      Buku(
          id: 1,
          judul: "The Poppy War",
          penulis: "R.F Kuang",
          genre: Genre.Historical,
          imgCover: "the_poppy_war",
          stok: 0,
          pages: 413,
          bahasa: "Indonesia",
          harga: "130.000",
          tipe: BookType.NonFiction),
    ];
  }
}
